BookStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;

namespace BookStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;
        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }

    }
}

BookStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
using BookStore.Models.ViewModels;

namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

BookStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card m-3 rounded">
    <div class="card-block m-2">
        <div class="card-body">
            <h3 class="card-title">
                <strong>@Model.Name</strong>
            </h3>

            <p class="card-text lead">
                @Model.Description
            </p>

            <span class="float-left bg-success text-white rounded m-2 p-1">
                @Model.Price.ToString("c")
            </span>

            <form id="@Model.ProductID" asp-action="AddToCart"
                  asp-controller="Cart" method="post" class="float-right m-2 p-1">
                <input type="hidden" asp-for="ProductID" />
                <input type="hidden" name="returnUrl"
                       value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-info btn-sm float-right">
                    Add To Cart
                </button>
            </form>

        </div>
    </div>
</div>

BookStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js"></script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>@ViewBag.Title</h4>
                <a class="btn btn-sm btn-primary float-right" asp-action="Logout" asp-
                   controller="Account">Log Out</a>
            </div>
            <div class="card-body">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    <title>BookStore</title>
</head>
<body>
    <nav class="navbar navbar-inverse bg-info justify-content-between">
        <a class="navbar-brand text-white" href="#">BOOK STORE</a>
       <div class="float-right">
            @await Component.InvokeAsync("CartSummary")
       </div> 
    </nav>
    <div class="container">
        <div class="row">
            <div class="col col-md-3">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>